services:
  ark-server:
    image: acekorneya/asa_server:2_1_latest
    container_name: ${CONTAINER_NAME}
    depends_on:
      - ark-config
    ports:
      - "${GAME_PORT}:${GAME_PORT}/tcp"       # Game port (TCP)
      - "${GAME_PORT}:${GAME_PORT}/udp"       # Game port (UDP)
      - "${RCON_PORT}:${RCON_PORT}/tcp"       # RCON port
    volumes:
      - ark_server_files:/home/pok/arkserver
      - ark_saved_data:/home/pok/arkserver/ShooterGame/Saved
    restart: ${RESTART_POLICY}
    environment:
      - INSTANCE_NAME=${CONTAINER_NAME}
      - TZ=America/Chicago
      - MAP_NAME=${MAP}
      - SESSION_NAME=${SERVER_NAME}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - ASA_PORT=${GAME_PORT}
      - RCON_PORT=${RCON_PORT}
      - RCON_ENABLED=${RCON_ENABLED}
      - SERVER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - UPDATE_SERVER=${UPDATE_ON_BOOT}
      - RANDOM_STARTUP_DELAY=FALSE
      - BATTLEEYE=FALSE
      - API=FALSE
      - CUSTOM_SERVER_ARGS=-UseDynamicConfig -CustomDynamicConfigUrl=http://ark-config:80/GameUserSettings.ini
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}

  ark-config:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME}-config
    volumes:
      - ark_dynamic_config:/usr/share/nginx/html:ro
    restart: ${RESTART_POLICY}

volumes:
  ark_server_files:
    external: true
    name: ${SERVER_FILES_VOLUME}
  ark_saved_data:
    external: true
    name: ${VOLUME_NAME}
  ark_dynamic_config:
    external: true
    name: ${DYNAMIC_CONFIG_VOLUME}
