services:
  ark-server:
    image: acekorneya/asa_server:2_1_latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${GAME_PORT}:7777/tcp"       # Game port (TCP)
      - "${GAME_PORT}:7777/udp"       # Game port (UDP)
      - "${RCON_PORT}:27020/tcp"      # RCON port
    volumes:
      - ark_server_files:/home/pok/arkserver
      - ark_saved_data:/home/pok/arkserver/ShooterGame/Saved
    restart: ${RESTART_POLICY}
    environment:
      - INSTANCE_NAME=${CONTAINER_NAME}
      - TZ=America/Chicago
      - MAP_NAME=${MAP}
      - SESSION_NAME=${SERVER_NAME}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - ASA_PORT=7777
      - RCON_PORT=27020
      - RCON_ENABLED=${RCON_ENABLED}
      - SERVER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - UPDATE_SERVER=${UPDATE_ON_BOOT}
      - RANDOM_STARTUP_DELAY=FALSE
      - BATTLEEYE=FALSE
      - API=FALSE
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}

volumes:
  ark_server_files:
    external: true
    name: ${SERVER_FILES_VOLUME}
  ark_saved_data:
    external: true
    name: ${VOLUME_NAME}
