services:
  smalland-server:
    image: smalland-server:latest
    container_name: ${CONTAINER_NAME}
    stop_grace_period: 30s
    ports:
      - "${GAME_PORT}:7777/udp"
    volumes:
      - smalland_data:/home/steam/smalland
    restart: ${RESTART_POLICY}
    environment:
      - UPDATE_ON_START=${UPDATE_ON_START}
      - SERVER_NAME=${SERVER_NAME}
      - WORLD_NAME=${WORLD_NAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - FRIENDLY_FIRE=${FRIENDLY_FIRE}
      - PEACEFUL_MODE=${PEACEFUL_MODE}
      - KEEP_INVENTORY=${KEEP_INVENTORY}
      - NO_DETERIORATION=${NO_DETERIORATION}
      - TAMED_CREATURES_IMMORTAL=${TAMED_CREATURES_IMMORTAL}
      - PRIVATE=${PRIVATE}
      - CROSSPLAY=${CROSSPLAY}
      - LENGTH_OF_DAY_SECONDS=${LENGTH_OF_DAY_SECONDS}
      - LENGTH_OF_SEASON_SECONDS=${LENGTH_OF_SEASON_SECONDS}
      - CREATURE_HEALTH_MODIFIER=${CREATURE_HEALTH_MODIFIER}
      - CREATURE_DAMAGE_MODIFIER=${CREATURE_DAMAGE_MODIFIER}
      - CREATURE_RESPAWN_RATE_MODIFIER=${CREATURE_RESPAWN_RATE_MODIFIER}
      - RESOURCE_RESPAWN_RATE_MODIFIER=${RESOURCE_RESPAWN_RATE_MODIFIER}
      - CREATURE_SPAWN_CHANCE_MODIFIER=${CREATURE_SPAWN_CHANCE_MODIFIER}
      - CRAFTING_TIME_MODIFIER=${CRAFTING_TIME_MODIFIER}
      - CRAFTING_FUEL_MODIFIER=${CRAFTING_FUEL_MODIFIER}
      - STORM_FREQUENCY_MODIFIER=${STORM_FREQUENCY_MODIFIER}
      - NOURISHMENT_LOSS_MODIFIER=${NOURISHMENT_LOSS_MODIFIER}
      - FALL_DAMAGE_MODIFIER=${FALL_DAMAGE_MODIFIER}
      - EOS_DEPLOYMENT_ID=${EOS_DEPLOYMENT_ID}
      - EOS_CLIENT_ID=${EOS_CLIENT_ID}
      - EOS_CLIENT_SECRET=${EOS_CLIENT_SECRET}
      - EOS_PRIVATE_KEY=${EOS_PRIVATE_KEY}
      - SERVER_PORT=7777
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}

volumes:
  smalland_data:
    external: true
    name: ${VOLUME_NAME}
