#!/bin/bash
set -euo pipefail

# Cron Setup Helper for Automated Backups
# Sets up scheduled backups for the new instance + preset architecture

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

# Source dependencies
source "$PROJECT_ROOT/scripts/shared/server-utils.sh"

show_usage() {
    cat << EOF
Cron Setup Helper for Game Server Backups

USAGE:
  $0 [OPTIONS]

OPTIONS:
  --install        Install cron jobs based on infrastructure configuration
  --remove         Remove existing game server backup cron jobs
  --list           Show current game server backup cron jobs
  --dry-run        Show what cron jobs would be created without installing
  --user <user>    Target user for cron jobs (default: current user)
  -h, --help       Show this help

EXAMPLES:
  $0 --install              # Install cron jobs for all environments
  $0 --list                 # Show current backup cron jobs
  $0 --dry-run              # Preview cron jobs without installing
  $0 --remove               # Remove all game server backup cron jobs

EOF
}

# Parse arguments
OPERATION=""
DRY_RUN=false
TARGET_USER=$(whoami)

parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --install)
                OPERATION="install"
                shift
                ;;
            --remove)
                OPERATION="remove"
                shift
                ;;
            --list)
                OPERATION="list"
                shift
                ;;
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --user)
                TARGET_USER="$2"
                shift 2
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                log_error "Unknown argument: $1"
                show_usage
                exit 1
                ;;
        esac
    done
    
    if [[ -z "$OPERATION" ]]; then
        log_error "Operation required (--install, --remove, or --list)"
        show_usage
        exit 1
    fi
}

# Get backup schedule from infrastructure config
get_backup_schedule() {
    local env="$1"
    local default_schedule="0 */6 * * *"  # Every 6 hours default
    
    # Try to get schedule from first available game config for this env
    local schedule="$default_schedule"
    for game_dir in "$PROJECT_ROOT"/games/*/; do
        local game=$(basename "$game_dir")
        local config=$(get_game_env_config "$game" "$env")
        if [[ -f "$config" ]] && command -v jq >/dev/null 2>&1; then
            schedule=$(jq -r '.backup_config.backup_schedule // "0 */6 * * *"' "$config")
            break
        fi
    done
    echo "$schedule"
}

# Generate cron job entry
generate_cron_entry() {
    local env="$1"
    local schedule=$(get_backup_schedule "$env")
    local script_path="$PROJECT_ROOT/scripts/automation/scheduled-backup.sh"
    local log_file="/var/log/gameserver-backup-${env}.log"
    
    # Cron job entry with proper logging
    echo "# Automated backup for $env environment - Generated by GameServerAdministration"
    echo "$schedule $script_path --env $env --game all --quiet >> $log_file 2>&1"
    echo ""
}

# Install cron jobs
install_cron_jobs() {
    log_info "Installing automated backup cron jobs..."
    
    # Check if environments exist
    local environments=()
    # Discover environments from game configs
    for env_file in "$PROJECT_ROOT"/games/*/environments/*.json; do
        if [[ -f "$env_file" ]]; then
            local env_name=$(basename "$env_file" .json)
            if [[ "$env_name" == "staging" || "$env_name" == "production" ]]; then
                # Only add if not already in list
                local already_added=false
                for existing in "${environments[@]+"${environments[@]}"}"; do
                    [[ "$existing" == "$env_name" ]] && already_added=true
                done
                [[ "$already_added" == false ]] && environments+=("$env_name")
            fi
        fi
    done
    
    if [[ ${#environments[@]} -eq 0 ]]; then
        log_error "No valid environments found (staging/production)"
        return 1
    fi
    
    # Generate cron entries
    local temp_cron=$(mktemp)
    
    # Preserve existing non-gameserver cron jobs
    crontab -l 2>/dev/null | grep -v "GameServerAdministration" > "$temp_cron" || true
    
    # Add header comment
    cat >> "$temp_cron" << EOF

# =================================================
# Game Server Automated Backups
# Managed by GameServerAdministration
# Generated on: $(date)
# =================================================

EOF
    
    # Add cron job for each environment
    for env in "${environments[@]}"; do
        log_info "Adding cron job for $env environment"
        generate_cron_entry "$env" >> "$temp_cron"
    done
    
    # Add footer comment
    cat >> "$temp_cron" << EOF
# =================================================
# End Game Server Automated Backups
# =================================================

EOF
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would install the following cron jobs:"
        echo "--- Cron jobs ---"
        grep -A 20 -B 5 "GameServerAdministration" "$temp_cron" || cat "$temp_cron"
        rm -f "$temp_cron"
        return 0
    fi
    
    # Install the new crontab
    if crontab "$temp_cron"; then
        log_success "Cron jobs installed successfully"
        
        # Ensure log directory exists
        sudo mkdir -p /var/log
        sudo touch /var/log/gameserver-backup-staging.log /var/log/gameserver-backup-production.log
        sudo chown "$TARGET_USER:$TARGET_USER" /var/log/gameserver-backup-*.log 2>/dev/null || true
        
        log_info "Log files created:"
        for env in "${environments[@]}"; do
            log_info "  - /var/log/gameserver-backup-${env}.log"
        done
        
    else
        log_error "Failed to install cron jobs"
        rm -f "$temp_cron"
        return 1
    fi
    
    rm -f "$temp_cron"
}

# Remove cron jobs
remove_cron_jobs() {
    log_info "Removing game server backup cron jobs..."
    
    # Get current crontab without game server entries
    local temp_cron=$(mktemp)
    crontab -l 2>/dev/null | grep -v "GameServerAdministration\|gameserver-backup" > "$temp_cron" || true
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would remove game server backup cron jobs"
        return 0
    fi
    
    # Install cleaned crontab
    if crontab "$temp_cron"; then
        log_success "Game server backup cron jobs removed"
    else
        log_error "Failed to remove cron jobs"
        rm -f "$temp_cron"
        return 1
    fi
    
    rm -f "$temp_cron"
}

# List current cron jobs
list_cron_jobs() {
    log_info "Current game server backup cron jobs:"
    
    local cron_content=$(crontab -l 2>/dev/null || echo "")
    
    if echo "$cron_content" | grep -q "GameServerAdministration\|gameserver-backup"; then
        echo "--- Game Server Backup Cron Jobs ---"
        echo "$cron_content" | grep -A 1 -B 1 "GameServerAdministration\|gameserver-backup" | grep -v "^--$"
        echo ""
        
        # Show log file status
        log_info "Backup log files:"
        for log_file in /var/log/gameserver-backup-*.log; do
            if [[ -f "$log_file" ]]; then
                local size=$(du -sh "$log_file" 2>/dev/null | cut -f1)
                local last_modified=$(stat -c "%y" "$log_file" 2>/dev/null | cut -d' ' -f1)
                log_info "  - $(basename "$log_file"): $size (last modified: $last_modified)"
            fi
        done
    else
        log_info "No game server backup cron jobs found"
    fi
}

# Validate setup
validate_setup() {
    log_info "Validating backup setup..."
    
    # Check if scheduled-backup.sh exists and is executable
    local backup_script="$PROJECT_ROOT/scripts/automation/scheduled-backup.sh"
    if [[ ! -x "$backup_script" ]]; then
        log_error "Backup script not found or not executable: $backup_script"
        return 1
    fi
    
    # Check if environments exist
    local valid_envs=0
    for env in staging production; do
        # Check if any game has a config for this environment
        local found=false
        for config in "$PROJECT_ROOT"/games/*/environments/${env}.json; do
            [[ -f "$config" ]] && found=true && break
        done
        if [[ "$found" == true ]]; then
            ((valid_envs++))
            log_success "Environment found: $env"
        else
            log_warning "Environment not found: $env"
        fi
    done
    
    if [[ $valid_envs -eq 0 ]]; then
        log_error "No valid environments found"
        return 1
    fi
    
    # Test dry run
    log_info "Testing backup script dry run..."
    if "$backup_script" --dry-run --env all --game all >/dev/null 2>&1; then
        log_success "Backup script test passed"
    else
        log_error "Backup script test failed"
        return 1
    fi
    
    log_success "Setup validation completed"
    return 0
}

# Show setup summary
show_summary() {
    local environments=(staging production)
    
    log_info "=== Backup Schedule Summary ==="
    for env in "${environments[@]}"; do
        local schedule=$(get_backup_schedule "$env")
        log_info "$env environment: $schedule"
    done
    
    log_info ""
    log_info "Backup locations:"
    log_info "  - Staging: $PROJECT_ROOT/backups/staging/"
    log_info "  - Production: $PROJECT_ROOT/backups/production/"
    log_info ""
    log_info "Log files:"
    log_info "  - Staging: /var/log/gameserver-backup-staging.log"
    log_info "  - Production: /var/log/gameserver-backup-production.log"
}

# Main execution
main() {
    parse_arguments "$@"
    
    case "$OPERATION" in
        "install")
            if validate_setup; then
                show_summary
                install_cron_jobs
            fi
            ;;
        "remove")
            remove_cron_jobs
            ;;
        "list")
            list_cron_jobs
            ;;
    esac
}

# Run main function with all arguments
main "$@"