services:
  palworld-server:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${GAME_PORT}:8211/udp"      # Game port
      - "${QUERY_PORT}:27015/udp"    # Query port
      - "${RCON_PORT}:25575/tcp"     # RCON port
      - "${RESTAPI_PORT}:8212/tcp"   # REST API port
    volumes:
      - palworld_saved_data:/palworld
    restart: ${RESTART_POLICY}
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - QUERY_PORT=27015
      - RCON_PORT=25575
      - REST_API_PORT=8212
      - PUBLIC_PORT=${GAME_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - COMMUNITY=true
      - MULTITHREADING=true
      - UPDATE_ON_BOOT=true
      - RCON_ENABLED=true
      - REST_API_ENABLED=true
      - DISABLE_GENERATE_SETTINGS=true
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}

volumes:
  palworld_saved_data:
    external: true
    name: ${VOLUME_NAME}
